### ISSUE TITLE
Add support for labels in boxed text

### ISSUE THREAD

**Issue by pdeffebach** [vega/vega-label#4]
Brought here over from the vega lite main repo https://github.com/vega/vega-lite/issues/4162

All the work on this looks fantastic, and thank you all for doing it. 

I want to highlight a feature of `ggrepel`, an R package that spaces labels well, that I particularly like.

![graph 1 -1](https://user-images.githubusercontent.com/23196228/45586149-53d82400-b8b7-11e8-94c3-fe2871ed2346.png)

I think having the labels boxed in like they are in this graph improves readability a lot and enables coloring in a way that would be difficult to parse with jus the label text alone. I also think its prettier than just text. 

Perhaps this feature could be on the radar for those working on this? 

Thank you

**Comment by chanwutk** [comment]
Hello,

Thank you for the suggestion! Since Vega is currently not supporting labeling, we would like to ship this basic version as soon as we can. Once we have Vega-Label shipped, we would be more than happy to add more features. :)

Ps. This can already be done with the current version of Vega-Label by drawing rectangle behind each label using [Reactive Geometry](https://vega.github.io/vega/docs/marks/).
